spring:
  application:
    name: eureka-discovery-server

server:
  port: ${EUREKA_PORT:8081}

eureka:
  client:
    register-with-eureka: false		# Esta propriedade indica se esta instância deverá se registrar ou não com um Eureka server.
    fetch-registry: false 			#Informar se a sua aplicação deve ou não buscar informações de Eureka server
  server:
    eviction-interval-timer-in-ms: 9000

info:
  tags:
    environment: development

---

spring:
  profiles: production

---

spring:
  profiles: test

---

spring:
  profiles: development
